forum/urls.py
from django.urls import path
from . import views

app_name='forum'

urlpatterns = [
        path('',views.index,name="index"),
        path('thread/<int:thread_id>',views.thread,name="thread"),
        path('newthread/',views.new_thread,name="newthread"),

]

solarstudy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('courses/',include('videos.urls')),
    path('instructor/',include('instructor.urls')),
    path('forum/',include('forum.urls')),
    path('membership/',include('subscriptions.urls')),





]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.urls import path
from .views import CourseListView,CourseDetailView,LessonDetailView

app_name="videos"

urlpatterns=[
    path('',CourseListView.as_view(),name='list'),
    path('<slug>/',CourseDetailView.as_view(),name='detail'),
    path('<course_slug>/<lesson_slug>/',LessonDetailView.as_view(),name='lesson-detail'),

]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from videos.models import Course

class Thread(models.Model):
    course=models.OneToOneField(Course,on_delete=models.CASCADE,null=True)
    title=models.CharField(max_length=200)
    description=models.TextField()
    date_created=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_latest_date(self):
        if self.reply_set.count()>0:
            return self.reply_set.latest('date_created').date_created
            
        return self.date_created



class Reply(models.Model):
    thread=models.ForeignKey(Thread,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    message=models.TextField()
    date_created=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username

forum/forms.py
from django.forms import ModelForm
from .models import Thread,Reply

class ThreadForm(ModelForm):
    class Meta:
        model=Thread
        fields=['title','description']


class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields=['message']

forum/views.py
from django.shortcuts import render,redirect
from .forms import ReplyForm,ThreadForm
from django.views.decorators.http import require_POST
from .models import Thread


def index(request):
    form=ThreadForm()
    threads=Thread.objects.all()

    context={
        'form':form,
        'threads':threads
    }
    return render(request,'forum/index.html',context)


def thread(request,thread_id):
    thread=Thread.objects.get(pk=thread_id)

    form = ReplyForm()

    if request.method=='POST':
        form=ReplyForm(request.POST)
        reply= form.save(commit=False) #to save in database
        reply.thread=thread
        reply.user=request.user
        reply.save()

        return redirect('forum:thread',thread_id=thread.id)

    context={'thread':thread , 'form':form }
    return render(request,'forum/thread.html',context)

@require_POST
def new_thread(request):
    form=ThreadForm(request.POST)
    thread=form.save()
    return redirect('forum:thread',thread_id=thread.id)

forum/templates/forum/index.html
{% extends 'landing/base.html' %}

{% block content %}

        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-lg-offset-0">
                <div class="card-body">
                        <h1 class="card-title">{{ course.title }}</h1>
                </div>
<a href="{% url 'videos:list'%}" class="btn btn-primary">Back</a>
                {% if user.is_authenticated %}
                    <div class="row">
                        <div class="col-lg-3">
                            <a href="#newModal" data-toggle="modal" class="btn btn-primary" title="Add Thread">
                                 Add Thread
                            </a>
                        </div>
                    </div>
                {% endif %}
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Last Post</th>
                        {% if user.is_authenticated %}
                        <th>Reply</th>
                        {% endif %}
                      </tr>
                    </thead>
                    <tbody>
                        {% for thread in threads %}
                      <tr>
                        <td><a href="{% url 'forum:thread' thread.id %}" style="font-size: 18px;" class="blue"> {{ thread.title }}</a></td>
                        <td> {{ thread.description }}</td>
                        <td> {{ thread.get_latest_date }}</td>
                        {% if user.is_authenticated %}
                        <td><a href="{% url 'forum:thread' thread.id %}"> Reply</a></td>
                        {% endif %}
                    </tr>
                      {% endfor %}
                    </tbody>
                  </table>

{% if user.is_authenticated %}

    <div class="modal fade" id="newModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <form action="{% url 'forum:newthread' %}" method="POST" role="form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="name">Thread Name</label>
                            <br>
                                {{ form.title }}
                        </div>
                        <div class="form-group" >
                            <label for="description">Description</label>
                            <br>
                            {{ form.description }}
                        </div>
                        
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    {% endblock %}
    

forum/templates/forum/thread.html
{% extends 'landing/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-lg-offset-0">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="card-body">
                        <a href="{% url 'forum:index' %}" class="btn btn-secondary">
                            Back to Threads 
                        </a>
                    </div>
                    </div>
                </div>

                <div class="row pad">
                    <div class="col-lg-12">
                        <div class="panel panel-primary">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="card-body">
                                    <div class="col-lg-12">
                                        <p style="font-size: 50px;" class="card-title">{{ thread.title}}</p> 
                                        <p>{{ thread.user.username }}</p>
                                    </div>
                                    <div class="col-lg-12">
                                        <p style="font-size: 30px;" class="card-text">{{ thread.description }}</p>
                                    </div>
                                </div>

                                    <div class="col-lg-12">
                                        <br />  
                                        {{ thread.date_created }}
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>

                <h3 class="">Replies &mdash; ( {{ thread.reply_set.count }}  total )</h3>

                {% for reply in thread.reply_set.all %}
                    <div class="card">
                        <div class="card-body">
                        <div class="panel panel-primary reply" id="r1" style="border-radius: 10px;">
                            <div class="panel-body">
                                <div class="row reply">
                                    <div class="col-lg-9">
                                        <div class="reply-msg">
                                            {{ reply.message }}
                                        </div>
                                    </div>
                                    <div class="col-lg-3">
                                        <div class="reply-details">
                                            {{ reply.date_created }} <br>
                                            {{ reply.user.username }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                <br>

{% if user.is_authenticated %}
                <div class="row pad">
                    <div class="col-lg-12 pad">
                        <div class="panel panel-primary">
                            <!-- <div class="panel-heading big">
                                <i class="glyphicon glyphicon-comment"></i> Post Reply
                            </div> -->
                            <div class="panel-body pad" id="_reply">
                                <form action="" method="POST" role="form" id="theForm">
                                        {% csrf_token %}
                                        <div class="card-body">
                                    <div style="width: 100%;"> 
                                    {{ form.message }}     
                                    </div>
                                
                                    <button 
                                        type="submit" 
                                        class="btn btn-primary">
                                        Submit
                                    </button>
                                </div>
                                </form>
                            </div>
                            {% else %}
                            <div class="card-body"> 
                                <p class="card-text">You can not reply. Please Login to reply.</p>
                               <a class="btn btn-link" href="{% url 'userprofile:login' %}">Login</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}

        </div>
    </div>
</div>

    {% endblock %}