forum/urls.py
from django.urls import path
from . import views

app_name='forum'

urlpatterns = [
        path('',views.index,name="index"),
        path('thread/<int:thread_id>',views.thread,name="thread"),
        path('newthread/',views.new_thread,name="newthread"),

]

solarstudy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('courses/',include('videos.urls')),
    path('instructor/',include('instructor.urls')),
    path('forum/',include('forum.urls')),
    path('membership/',include('subscriptions.urls')),





]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

subscriptions/urls.py
from django.urls import path
from . import views

app_name='membership'

urlpatterns = [
 path('',views.home,name="home"),
 path('checkout/',views.checkout,name="checkout"),


]

#  path('update-transaction/<subscription_id>/',views.updateTransactions,name="update_transaction"),

subscriptions/models.py
from django.db import models

videos/models.py
from django.db import models
from django.urls import reverse

class Course(models.Model):
    slug=models.SlugField()
    title=models.CharField(max_length=100)
    description=models.TextField()
    thumbnail=models.ImageField()
    date_posted=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('videos:detail',kwargs={'slug':self.slug})
        
    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')

class Lesson(models.Model):
    slug=models.SlugField()
    title=models.CharField(max_length=100)
    course=models.ForeignKey(Course,on_delete=models.SET_NULL,null=True)
    position=models.IntegerField()
    video_file=models.FileField()
    date_posted=models.DateTimeField(auto_now_add=True)
    next_slug=models.SlugField(null=True)

    def __str__(self):
        return self.course.title +" | "+ self.title

    def get_absolute_url(self):
        return reverse(
            'videos:lesson-detail',
            kwargs={
                'course_slug':self.course.slug,
                'lesson_slug':self.slug
                })
    def get_next_lesson(self):
        return reverse('videos:lesson-detail',
        kwargs={
            'course_slug':self.course.slug,
            'lesson_slug':self.next_slug
        })
  

subscriptions/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required(login_url='landing:login')
def home(request):
    return render(request,'subscriptions/join.html')

@login_required(login_url='landing:login')
def checkout(request):
    return render(request,'subscriptions/checkout.html')


# def paymentView(request):
#     user_membership=get_user_membership(request)
#     selected_membership=get_selected_membership(request)
#     publishKey=settings.STRIPE_PUBLISHABLE_KEY
#     if request.method =='POST':
#         try: 
#             token=request.POST['stripeToken']
#             subscription=stripe.Subscription.create(
#                 customer= user_membership.stripe_customer_id,
#                 items=[
#                     {
#                         "plan":selected_membership.stripe_plan_id,
#                     },
#                 ],
#                 source=token
#             )

#             return redirect(reverse('membership:update_transaction', 
#                     kwargs={
#                         'subscription_id':subscription.id

#             }))



#         except: stripe.CardError as e:
#             messages.info(request,"Your Card Has Been Declined")

#     context={
#         'publishKey':publishKey,
#         'selected_membership':selected_membership
#     }
#     return render(request,'subscriptions/membership_payment.html',context)



# def updateTransactions(request,subscription_id):
#     user_membership=get_user_membership(request)
#     selected_membership=get_selected_membership(request)

#     user_membership.membership=selected_membership
#     user_membership.save()

#     sub, created=Subscription.objects.get_or_create(user_membership=user_membership)
#     sub.stripe_subscription_id=subscription_id
#     sub.active=True
#     sub.save()

#     try:
#         del request.session['selected_membership_type']
#     except:
#         pass

#     messages.info(request,"Successfully Created {}".format(selected_membership))

#     return redirect('/')


# def get_user_membership(request):
#     user_membership_qs=UserMembership.objects.filter(user=request.user)
#     if user_membership_qs.exists():
#         return user_membership_qs.first()
#     return None


# def get_user_subscription(request):
#     user_subscription_qs=Subscription.objects.filter(user_membership=get_user_membership(request))
#     if user_subscription_qs.exists():
#         user_subscription=user_subscription_qs.first()
#         return user_subscription
#     return None


# def get_selected_membership(request):
#     membership_type=request.session['selected_membership_type']
#     selected_membership_qs=Membership.objects.filter(
#         membership_type=membership_type)
#     if selected_membership_qs.exists():
#         return selected_membership_qs.first()
#     return None




# class MembershipSelectView(ListView):
#     model=Membership

#     def get_context_data(self,*args,**kwargs):
#         context= super().get_context_data(**kwargs)
#         current_membership=get_user_membership(self.request)
#         context['current_membership']=str(current_membership.membership)
#         return context

#     def post(self,request,**kwargs):
#         selected_membership=request.POST.get('membership_type')
#         user_membership=get_user_membership(request)
#         user_subscription=get_user_subscription(request)
        
#         selected_membership_qs=Membership.objects.filter(
#             membership_type=selected_membership
#         )
#         if selected_membership_qs.exists():
#             selected_membership=selected_membership_qs.first()

#         ''''
#         ==============
#           VALIDATION
#         ==============
#         '''

#         if user_membership.membership == selected_membership:
#             if user_subscription != None:
#                 messages.info(request,"you already have this membership.\
#                 Your next payment is due {}".format('get this value from stripe'))
#                 return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


#         request.session['selected_membership_type']= selected_membership.membership_type
#         return HttpResponseRedirect(reverse('membership:payment'))

subscriptions/templates/subscriptions/checkout.html
{% extends 'landing/base.html' %}
{% block content %}
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-4 order-md-2 mb-4">
        <br>
        <br>
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your cart</span>
          <span class="badge badge-secondary badge-pill">1</span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">Solar Study Premium</h6>
              <small class="text-muted">Test</small>
            </div>
            <span class="text-muted">₹199</span>
          </li>
          
          <li class="list-group-item d-flex justify-content-between">
            <span>Total</span>
            <strong>₹199</strong>
          </li>
        </ul>
        
        <div class="text-center pt-3">
        <form action="" method="POST">
          {% csrf_token %}
          <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key=""
            data-amount="500"
            data-name="Solar Study Membership"
            data-description="Premium Membership"
            data-email="test@test.org"
            data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
            data-locale="auto">
          </script>
          <input type="hidden" value="" name="plan" />
          <input type="hidden" value="" name="coupon" />
        </form>
        </div>
        </div>
      </div>
      </div>


<hr>
{% endblock %}

subscriptions/templates/subscriptions/home.html
{% extends 'plans/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Nick Fitness</h1>
  <p class="lead">Fitness Is Fun</p>
  <a href="{% url 'join' %}"><button type="button" class="btn btn-lg btn-primary">Get Premium</button></a>
</div>

<div class="container">

  <h3>Trending Articles</h3>
  <ul>
    {% for plan in plans.all %}

    <li><a href="{% url 'plan' plan.id %}">{{ plan.title }}</a></li>

    {% endfor %}
  </ul>
</div>
{% endblock %}

subscriptions/templates/subscriptions/join.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Solar Study Membership</h1>
  <p class="lead"> Select from the below.</p>
</div>
<hr>
<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Monthly</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">₹199<small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>All Courses</li>
          <li>Forum and Doubt Assistance</li>
          <li>New Skills</li>
          <li>Certificates</li>
        </ul>
        <a href="{% url 'membership:checkout' %}"><button type="button" class="btn btn-lg btn-block btn-outline-primary">Get started</button></a>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Yearly<small class="text-primary">  Save ₹389 ! </small></h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">₹1999 <small class="text-muted">/ yr</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>All Courses</li>
          <li>Forum and Doubt Assistance</li>
          <li>New Skills</li>
          <li>Certificates</li>
        </ul>
        <a href="{% url 'membership:checkout' %}"><button type="button" class="btn btn-lg btn-block btn-outline-primary">Get started</button></a>
      </div>
    </div>
  </div>
</div>
<hr>
{% endblock %}

subscriptions/templates/subscriptions/membership_list.html
{% extends 'landing/base.html' %}


{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Solar Study Membership</h1>
    <p class="lead"> Select Your Plan.</p>
  </div>
  <hr>
  <div class="container">
    <div class="card-deck mb-3 text-center">

        {% for object in object_list %}
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{  object.membership_type }}</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title"> Price: ₹{{ object.price }}<small class="text-muted">/month</small></h1>
          <h4>Included Courses </h4>
          <ul class="list-unstyled mt-3 mb-4">
              {% for course in object.course_set.all %}
            <li>{{ course.title }}</li>
            {% endfor %}
          </ul>
          {% if object.membership_type != 'Free' %}
          <form action="{% url 'membership:home' %}" method="POST">
              {% csrf_token %}
              {% if object.membership_type != current_membership %}
              <input type="submit" class="btn btn-lg btn-block btn-warning" value="Select">
            {% else %}
            <small>This is your current membership </small>
            {% endif %}
            <input type="hidden" name="membership_type" value="{{ object.membership_type }}">
          </form>
          {% endif %}
        </div>
      </div>

      {% endfor %}
    </div>
  </div>
  <hr>

{% endblock %}

subscriptions/templates/subscriptions/plan.html
{% extends 'plans/base.html' %}
{% block content %}
<div class="container">
<h1>{{ plan.title}}</h1>
<p>{{ plan.text }}</p>
</div>
{% endblock %}