forum/urls.py
from django.urls import path
from . import views

app_name='forum'

urlpatterns = [
        path('',views.index,name="index"),
        path('thread/<int:thread_id>',views.thread,name="thread"),
        path('newthread/',views.new_thread,name="newthread"),

]

instructor/urls.py
from django.urls import path
from . import views

app_name="instructor"

urlpatterns=[
    path('',views.teacherProfile,name="home"),
    path('createcourse/',views.create_course,name="createcourse"),

   
]

landing/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name='landing'

urlpatterns = [
     path('',views.home,name="home"),
     path('terms/',views.terms,name="terms"),
     path('login/',views.loginUser,name="login"),
     path('signup/',views.signupUser,name="signup"),
     path('about/',views.about,name="about"),
     path('logout/',views.logoutUser,name="logout"),
     path('profile/',views.profile,name="profile"),


     path('password_reset/',
          auth_views.PasswordResetView.as_view(template_name='landing/password_reset.html',success_url=reverse_lazy('landing:password_reset_done')),
               name="password_reset"),

     path('password_reset_sent/',
          auth_views.PasswordResetDoneView.as_view(template_name='landing/password_reset_sent.html'),
          name="password_reset_done"),

     path('reset/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(template_name='landing/password_reset_form.html',success_url=reverse_lazy('landing:password_reset_complete')),
          name="password_reset_confirm"),

     path('password_reset_complete/',
          auth_views.PasswordResetCompleteView.as_view(template_name='landing/password_reset_done.html'),
          name="password_reset_complete"),

]

solarstudy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('courses/',include('videos.urls')),
    path('instructor/',include('instructor.urls')),
    path('forum/',include('forum.urls')),
    path('membership/',include('subscriptions.urls')),





]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

instructor/models.py
from django.db import models
from django.contrib.auth.models import User

instructor/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms

class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields=['first_name','last_name','username',
                    'email','password1','password2']

                    

instructor/views.py
from django.shortcuts import render,redirect
from landing.decorators import unauthenticated_user
from .forms import UserSignupForm
from django.contrib.auth.models import Group
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from videos.forms import CourseForm,LessonForm



# @allowed_users(allowed_roles=['admin','teacher'])
def home(request):
    return render(request,'instructor/home.html')


@unauthenticated_user
def signupteacher(request):
    form=UserSignupForm()
    if request.method =='POST':
        form=UserSignupForm(request.POST)
        if form.is_valid():
            teacher=form.save()
            username=form.cleaned_data.get('username')
            group=Group.objects.get(name='teacher')
            teacher.groups.add(group)
            messages.success(request, username +", Your Account has been successfully created! Login To continue ")
            return redirect('landing:login')
    context={'form':form}
    return render(request,'instructor/register.html',context)
    
@login_required(login_url="landing:login")
def teacherProfile(request):
    return render(request,'instructor/instructor_profile.html')


# @allowed_users(allowed_roles=['admin','teacher'])

@login_required(login_url='landing:login')
def create_course(request):
    form=CourseForm()
    if request.method=='POST':
        form=CourseForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('landing:profile')
    context={'form':form}
    return render(request,'instructor/create_course.html',context)

def edit_course():
    pass

def delete_course():
    pass

def view_course():
    pass

instructor/templates/instructor/create_course.html
{% extends 'landing/base.html' %}

{% block content %}


<div class="card card-body">

<form action="" method="POST" enctype= "multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}
    <input type="submit" value="Submit">

</form>
</div>

{% endblock %}

instructor/templates/instructor/home.html
{% extends 'landing/base.html' %}

{% block content %}

<h1 class="text-center">Welcome to Instructor Dashboard</h1>
<hr>

<br>
<div class="row">
    <div class="col-sm-4">
        <div class="card card-body">
            <h3 class="card-title">
                Want to Teach at Solar Study??
            </h3>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="card card-body">
            <h3 class="card-title">Fill the form </h3>
            <p class="card-text"> Our team will reach out to you.</p>
            <form action="{% url 'instructor:profile' %}" method="POST">
                {% csrf_token %}
                
                <input class="btn btn-success" type="submit" value="Submit">
            </form>
        </div>
    </div>
</div>
<hr>
{% endblock %}

instructor/templates/instructor/instructor_profile.html
{% extends 'landing/base.html' %}

{% block content %}

<style>

    .card-img-top{
        max-width: 200px;
        max-height: 200px;
        margin: 0 auto;
        }

</style>

<div class="card-body">
    <h1 class="card-title text-center">
        Instructor Dashboard
    </h1>
</div>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h3 style="color: cadetblue;" class="card-title text-center">
                    Your Courses
                </h3>

                
            </div>           
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-body">
                <a href="{% url 'instructor:createcourse' %}" class="btn btn-info">Create Course</a>
                <br>
                <br>
                <a href="" class="btn btn-info">Create SubCourse</a>
                <br>
                <br>
                <a href="" class="btn btn-info">Create Lesson</a>
                <br>
                <br>
                <a href="" class="btn btn-danger">Create Assignment</a>
                <br>
            </div>
        </div>
    </div>
</div>


<hr>
{% endblock %}